GENRE_MAPPING = {
    "aksi": "action",
    "drama": "drama",
    "fantasi": "fantasy",
    "horor": "horror",
    "komedi": "comedy",
    "lucu": "comedy",
    "misteri": "mystery",
    "olahraga": "sports",
    "romansa": "romance",
    "romantis": "romance",
    "sci fi": "sci fi",
    "scifi": "sci fi",
    "seram": "horror",
    "sol": "slice of life",
    "hidup hari hari":"slice of life",
    "supernatural": "supernatural",
    "tualang": "adventure",
    "masak": "gourmet",
    "tegang": "suspense"
    
}

THEME_MAPPING = {
    "musik": "music",
    "bela diri": "martial arts",
    "detektif": "detective",
    "dunia lain": "isekai",
    "game": "video game",
    "harem": "harem",
    "idol": "idols female",
    "isekai": "isekai",
    "mahou shoujo": "mahou shoujo",
    "mecha": "mecha",
    "militer": "military",
    "musik": "music",
    "psikologis": "psychological",
    "reinkarnasi": "reincarnation",
    "robot": "mecha",
    "sejarah": "historical",
    "sekolah": "school",
    "super power": "super power",
    "time travel": "time travel",
    "vampir": "vampire",
}
